In [1]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [2]:
Arr = np.arange(25).reshape(5,5)

Arr[[0,1]] = Arr[[1,0]]

print(Arr)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**75. How to compute averages using a sliding window over an array?**

In [6]:
array = np.random.randint(1,10, size=(3,3))
print (array)
a = np.cumsum(array)
print("\n")
print (a)
print ("Average:", round(np.average(a),2))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
